server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bionest
    username: root
    password: sa123
  #    url: jdbc:mysql://192.168.241.150:3306/bionest
#    username: root
#    password: Root@123456789!

  jpa:
    hibernate:
      ddl-auto: update